title: Wonbeom LEE
description: CV of Wonbeom LEE
url: https://wonbeom.github.io
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
