title: Alvin Son
description: CV of Alvin Son
url: https://alvin-son.github.io/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml

# Analytics
# analytics:
#   provider               : "google-gtag" 
#                           # false (default), "google", "google-universal", "google-gtag", "custom"
#   google:
#     tracking_id          : "G-GV57EY9XL5"
#     anonymize_ip         : # true, false (default)
