title: Wonbeom Lee
description: CV of Wonbeom Lee
url: https://leewonbeom.github.io
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
